Improvements worflows set env:variables

diff --git a/.github/workflows/snowpark_checkpoints_configuration-use-set-artifacts.yml b/.github/workflows/snowpark_checkpoints_configuration-use-set-artifacts.yml
--- a/.github/workflows/snowpark_checkpoints_configuration-use-set-artifacts.yml
+++ b/.github/workflows/snowpark_checkpoints_configuration-use-set-artifacts.yml
@@ -7,6 +7,9 @@ on:
         required: true
         type: string
 
+env:
+  PYTHON_VERSION: "3.11"
+
 jobs:
   artifacts:
     name: Create artifacts
@@ -20,39 +23,53 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: "8.0.x"
+      - name: Fetch tags
+        run: git fetch --tags
 
-      - name: Install GitVersion.Tool
+      - name: Get version from tag
+        id: get_version
         run: |
-          dotnet tool install --global GitVersion.Tool
-          echo "export PATH=\$PATH:\$HOME/.dotnet/tools" >> $GITHUB_ENV
+          if [[ $GITHUB_REF == refs/tags/* ]]; then
+            VERSION=${GITHUB_REF#refs/tags/}
+            VERSION=${VERSION#v}
+            echo "version=$VERSION"
+          else
+            echo "GIT REF is not a tag"
+            VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
+            VERSION=${VERSION#v}
+            echo "version=$VERSION"
+          fi
 
-      - name: Generate Version with GitVersion
-        id: gitversion
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?$ ]]; then
+            echo "version=$VERSION"
+            echo "Error: No version found"
+            exit 1
+          fi
+
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+
+      - name: Set Version
         run: |
-          version_info=$(dotnet gitversion /output json /showvariable InformationalVersion)
-          version_output=$(dotnet gitversion /output json /showvariable MajorMinorPatch)
-          echo "Calculated Version: $version_output" && echo "Informational Version: $version_info"
-          echo "version=$version_output" >> $GITHUB_OUTPUT
+          echo "Current directory: $PWD" && ls -l
+          echo "Updating pip file ${FILE_NAME} with version: ${NEW_VERSION}"
+          find $(pwd) -name "${FILE_NAME}" -exec sh -c 'sed -i "s/{% set version = \".*\" %}/{% set version = \"${NEW_VERSION}\" %}/" "$1"' _ {} \;
         env:
-          DOTNET_ROOT: $HOME/.dotnet
+          NEW_VERSION: ${{ steps.get_version.outputs.version }}
+          FILE_VERSION: __version__.py
+        working-directory: ./snowpark-checkpoints-configuration
 
-      - name: Update Version
+      - name: Get Version Info
         run: |
-          sed -i "s/^__version__ = \".*\"/__version__ = \"${NEW_VERSION}\"/" ${FILE_VERSION}
-          echo "Package Version updated:" && cat ${FILE_VERSION}
+          echo "Displaying updated meta.yaml files:"
+          find $(pwd) -name "${FILE_NAME}" -exec sh -c 'echo "File: $1" && grep "__version__" $1' _ {} \;
         env:
-          NEW_VERSION: ${{ steps.gitversion.outputs.version }}
-          FILE_VERSION: ../snowpark-checkpoints-configuration/__version__.py
+          FILE_NAME: __version__.py
         working-directory: ./snowpark-checkpoints-configuration
 
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.10"
+          python-version: "${{ env.PYTHON_VERSION }}"
 
       - name: Install required tools
         run: |
